### ISSUE TITLE
Is this plugin still actively maintained?

### ISSUE THREAD

**Issue by njam** [voxpupuli/vagrant-librarian-puppet#52]
@jhoblitt @mhahn is this plugin still actively maintained?

The librarian-puppet gem [has recently been moved](https://github.com/rodjek/librarian-puppet/issues/337) to the [voxpupuli collective](https://voxpupuli.org/)'s github organization.

In case you don't have the time to maintain this plugin anymore, maybe they are up to adopt it. Then there can be a few maintainers and we can guarantee the active development of the plugin. wdyt?

**Comment by mhahn** [comment]
I'm definitely not working on this anymore. Happy to pass it on to whomever.

**Comment by njam** [comment]
@jhoblitt wdyt, should I reach out to voxpupuli?

**Comment by njam** [comment]
@mhahn @jhoblitt voxpupuli would be up for adopting the plugin!

I think it would be best to transfer the repo over to the "voxpupuli" organization, which would transfer all issues as well, and install redirects from the old to the new repo URL. wdyt?

@igalic added out to a "admin group" on "voxpupuli" which allows you to do transfer the repo.
See https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts

**Comment by jhoblitt** [comment]
I'd be happy with the repo being migrated to voxpupuli but I am intended to continue to do maintenance.

**Comment by njam** [comment]
That sounds great! I'd be happy to help out where I can as well.

@mhahn if you want, you should be able to move the repo to "voxpupuli" now I think.

**Comment by gesinn-it** [comment]
Are there any new on this?

**Comment by njam** [comment]
@mhahn @jhoblitt are you still up for moving this repo to voxpupli?
If so, you should be able to move it according to https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts

**Comment by igalic** [comment]
![invoices1](https://cloud.githubusercontent.com/assets/497249/14853079/477f1f0a-0c8a-11e6-9ff6-e5b683791353.png)

**Comment by jhoblitt** [comment]
I'm a repo collab but not an owner, so I can't do a transfer.  I'm also not a team member of the voxpupuli org.

**Comment by mhahn** [comment]
hey all, sorry for the delay i know that is really annoying but this got lost in noise of github and work.

repo is transferred, lmk if i can do anything else!

**Comment by njam** [comment]
👍 thanks.

@igalic could you add @jhoblitt as a collaborator as well, as he was maintaining the project already?

**Comment by igalic** [comment]
i am ***shocked*** that @jhoblitt isn't already a collaborator.

**Comment by jhoblitt** [comment]
@igalic It has been a very convenient excuse up to this point ;)
